# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: uTorrent.uTorrent
PackageVersion: (3.5.5)
Installers:
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://download-hr.utorrent.com/track/stable/endpoint/utorrent/os/windows
  InstallerSha256: F72EE83436CB1F82366BFAAFB14A4C0CB99826C02166FC0BD21FB6E7EB5190C6
ManifestType: installer
ManifestVersion: 1.2.0

